"""engines/conviction_sizing.py — DEPRECATED SHIM (v33 Fix Pack)

═══════════════════════════════════════════════════════════════════════════
⚠️  DO NOT EDIT THIS FILE. DO NOT ADD LOGIC HERE.
═══════════════════════════════════════════════════════════════════════════

This file used to contain Soros/Druckenmiller conviction sizing logic with
grade multipliers (A=2.5x, A+=3.0x) that CONFLICTED with portfolio_sizing.py
(A=1.20x, A+=1.40x).

Risk before this fix: orchestrator could call the wrong sizer → 2-3x oversizing
on grade-A signals → silent capital risk.

POST-FIX BEHAVIOR:
  • All calls to `calculate_size()` and `run_sizing()` are FORWARDED to
    portfolio_sizing.calculate_position_size() / run_portfolio_sizing().
  • A `DeprecationWarning` fires at import time so logs surface stale callers.
  • Output shape is back-compat: returns the keys old callers expected
    ("ticker", "size_pct", "size_dollar", "mode", "rationale", "multipliers").

MIGRATION:
  Replace:
      from engines.conviction_sizing import run_sizing
      result = run_sizing(alpha_items, gamma, greeks, boom_bust, reflex, pv)
  With:
      from engines.portfolio_sizing import run_portfolio_sizing
      result = run_portfolio_sizing(
          alpha_items, portfolio_value=pv,
          quad=..., stage=..., gamma_data=..., greeks_data=..., reflexivity=...,
      )

Schedule for hard removal: v34. Until then, this shim keeps callers alive.
"""
from __future__ import annotations

import warnings
from typing import Dict, List

from engines.portfolio_sizing import (
    calculate_position_size,
    run_portfolio_sizing,
)

warnings.warn(
    "engines.conviction_sizing is DEPRECATED. "
    "Use engines.portfolio_sizing.run_portfolio_sizing() instead. "
    "Slated for removal in v34.",
    DeprecationWarning,
    stacklevel=2,
)


def _back_compat_shape(new_result: Dict) -> Dict:
    """Map portfolio_sizing v2 output to legacy conviction_sizing keys."""
    return {
        "ticker": new_result.get("ticker", ""),
        # legacy used "size_pct" as 0-100 scale; v2 uses 0-1
        "size_pct": round(new_result.get("target_pct", 0.0) * 100, 2),
        "size_dollar": new_result.get("target_dollar", 0),
        "mode": new_result.get("mode", "❌ SKIP"),
        "base_pct": 2.0,  # legacy constant, retained for compat
        "multipliers": new_result.get("multipliers", {}),
        "rationale": new_result.get("rationale", ""),
        # NEW: surface that legacy caller used a deprecated path
        "_deprecated_via": "conviction_sizing_shim",
    }


def calculate_size(
    ticker: str,
    row: Dict,
    gamma: Dict,
    greek: Dict,
    boom_bust_stage: str,
    reflexivity_score: float,
    portfolio_value: float = 100_000,
) -> Dict:
    """Legacy entrypoint — forwards to portfolio_sizing.calculate_position_size."""
    warnings.warn(
        "calculate_size() is deprecated. Use portfolio_sizing.calculate_position_size().",
        DeprecationWarning,
        stacklevel=2,
    )
    # row carries grade/direction/rr/near_entry already
    new_result = calculate_position_size(
        ticker=ticker,
        signal=row,
        portfolio_value=portfolio_value,
        quad=row.get("quad", "Q3"),  # legacy didn't pass quad — fallback Q3
        stage=boom_bust_stage,
        current_positions=row.get("current_positions", {}),
        gamma=gamma or {},
        greek=greek or {},
        reflexivity_score=reflexivity_score,
    )
    return _back_compat_shape(new_result)


def run_sizing(
    alpha_items: List[Dict],
    gamma_data: Dict,
    greeks_data: Dict,
    boom_bust: Dict,
    reflexivity: Dict,
    portfolio_value: float = 100_000,
) -> Dict[str, Dict]:
    """Legacy bulk entrypoint — forwards to portfolio_sizing.run_portfolio_sizing.

    Legacy returned {ticker: result_dict}. portfolio_sizing returns a single
    aggregate dict with "positions": [...]. We reshape to legacy.
    """
    warnings.warn(
        "run_sizing() is deprecated. Use portfolio_sizing.run_portfolio_sizing().",
        DeprecationWarning,
        stacklevel=2,
    )
    quad = (boom_bust or {}).get("quad", "Q3")
    stage = (boom_bust or {}).get("stage", "INCEPTION")

    agg = run_portfolio_sizing(
        alpha_items=alpha_items or [],
        portfolio_value=portfolio_value,
        quad=quad,
        stage=stage,
        gamma_data=gamma_data or {},
        greeks_data=greeks_data or {},
        reflexivity=reflexivity or {},
        current_positions={},
    )

    out: Dict[str, Dict] = {}
    for pos in agg.get("positions", []):
        t = pos.get("ticker", "")
        if t:
            out[t] = _back_compat_shape(pos)
    return out


__all__ = ["calculate_size", "run_sizing"]
